language: python

matrix:
  include:
    - python: 3.6-dev
      env: TOXENV=coveralls
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5-dev
      env: TOXENV=py35
    - python: 3.6-dev
      env: TOXENV=py36

sudo: required
dist: trusty

before_install:
  - sudo apt-get -qq update

install:
  - pip install -U tox

script:
  - tox
