language: python

matrix:
  include:
    - python: 3.8-dev
      env: TOXENV=coveralls
    - python: 3.5-dev
      env: TOXENV=py35
    - python: 3.6-dev
      env: TOXENV=py36
    - python: 3.7-dev
      env: TOXENV=py37
    - python: 3.8-dev
      env: TOXENV=py38

sudo: required
dist: bionic

before_install:
  - sudo apt-get -qq update

install:
  - pip install -U tox

script:
  - tox
